name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # เปลี่ยนเป็น branch หลักของคุณ

permissions:
  contents: write # ✅ ให้สิทธิ์ GitHub Actions Push ได้

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # ✅ ปิด credentials เดิม

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }} # ✅ ใช้ Built-in GitHub Token
